logging:
  level:
    org.hibernate:
      sql: debug
      orm.jdbc.bind: trace
spring:
  application.name: ecommerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: newgeniee
    password: aa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 50
        default-page-size: 10

springdoc:
  packages-to-scan: hhplus.newgeniee.ecommerce
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache.disabled: true

  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
    swagger-ui:
      enabled: true
      path: /docs
      tags-sorter: alpha
      operations-sorter: alpha

